### ISSUE TITLE
Heroku certificate error on SSO

### ISSUE THREAD

**Issue by soumyaray** [servsecCrucible/pixeltrackAPP#29]
I think I know why you're getting the certificate error on SSO.  Your callback URL seems to go to app.heroku.com or somesuch.  the certificate (and your host) should be *.herokuapp.com

**Comment by rjollet** [comment]
Yes I just correct it and it seems working now. I will see if it solve the issue we have with tracker to

**Comment by rjollet** [comment]
Greats it works, thanks

**Comment by soumyaray** [comment]
happy to contribute!
